development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: api_gateway_app_development
  pool:     5
  username: bitcanny
  password: root
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: api_gateway_app_test
  pool:     5
  username: bitcanny
  password: root
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: api_gateway_app_production
  pool:     5
  username: bitcanny
  password: root
  template: template0
